### ISSUE TITLE
"python main.py --test" error if "log_path" configured

### ISSUE THREAD

**Issue by borisovg** [cbess/text-sherlock#23]
contents of local_settings.yml:

```
log_path: '/home/borisov/log/'
```

error:

```
(sherlock_env) borisov@deli:~/src/text-sherlock $ python main.py --test
Loaded Sherlock config settings from /home/borisov/src/text-sherlock/local_settings.yml
Xapian backend support unavailable
Running sherlock...
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    run()
  File "main.py", line 77, in run
    import tests
  File "/home/borisov/src/text-sherlock/tests/__init__.py", line 17, in <module>
    hdlr = logging.FileHandler(os.path.join(settings.LOG_PATH, filename, __name__))
  File "/usr/lib/python2.7/logging/__init__.py", line 905, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 935, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/borisov/log/sherlock.tests.log.txt/tests'
```

**Comment by cbess** [comment]
Thanks for the bug report. I'll remove the trailing *module* name.
